package com.mobis.enumeradores;

public enum EnumErros {
    SEM_ERRO,
    ERRO,
    PASSAGEIRO_NAO_INFORMADO,
    OBSERVACAO_NAO_INFORMADO,
    LIMITE_MAXIMO_PASSAGEIRO,
    PASSAGEIRO_JA_INFORMADO,
    DATA_HORA_MENOR_QUE_ATUAL,
    DATA_HORA_INVALIDA,
    DATA_INVALIDA,
    DATA_MENOR_QUE_ATUAL,
    DATA_INICIAL_INVALIDA,
    DATA_FINAL_INVALIDA,
    DATA_INICIAL_DEVE_SER_MENOR,
    FINALIZANDO_VIAGEM_ANTES,
}
